# Generated by Django 3.0.4 on 2020-03-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=256)),
                ('body_html', models.TextField(blank=True)),
                ('image', models.URLField(blank=True)),
            ],
        ),
    ]
