# Generated by Django 3.0.4 on 2020-03-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_inventory_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='available',
            field=models.IntegerField(default=0),
        ),
    ]
