# Generated by Django 3.0.4 on 2020-03-20 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='inventory_item_id',
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', models.IntegerField(blank=True)),
                ('inventory_item_id', models.TextField(blank=True, default='', max_length=32)),
                ('inventory_quantity', models.IntegerField(blank=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Inventory')),
            ],
        ),
    ]
